using ExamPortal.Data;
using ExamPortal.Models;
using ExamPortal.Configuration;
using Microsoft.Extensions.Options;

namespace ExamPortal.Services
{
    /// <summary>
    /// Single source of truth for issuing an assessment invitation. Previously
    /// AdminController (SendInvitation/ResendInvitation) and RecruiterController
    /// (AssignAssessment) each built invitations independently, which had drifted:
    /// admin-issued invitations had no one-time login token and no AssessmentDate
    /// gate, used a hardcoded 7-day expiry, and ResendInvitation didn't send an
    /// email at all. Routing every caller through this one method means a
    /// candidate gets the same login options, the same email content, and the
    /// same scheduling/expiry behavior no matter who on the team sent the invite.
    /// </summary>
    public class AssessmentInvitationService
    {
        /// <summary>Default link validity when a caller doesn't specify one (7 days), matching
        /// the admin flow's previous hardcoded behavior.</summary>
        public const int DefaultExpiryHours = 24 * 7;

        private readonly AppDbContext _db;
        private readonly NotificationService _notifications;
        private readonly EmailOptions _emailOptions;

        public AssessmentInvitationService(AppDbContext db, NotificationService notifications, IOptions<EmailOptions> emailOptions)
        {
            _db = db;
            _notifications = notifications;
            _emailOptions = emailOptions.Value;
        }

        /// <summary>
        /// Revokes any existing invitations for this candidate/exam matching
        /// <paramref name="statusesToRevoke"/>, creates a fresh invitation (secure link token +
        /// one-time numeric login token), advances the candidate to InvitationSent, and queues
        /// the invitation email. Caller is still responsible for calling SaveChanges().
        /// </summary>
        /// <param name="secureToken">The link token to use for this invitation — generated by
        /// the caller via <see cref="GenerateSecureToken"/> *before* calling this method, so the
        /// caller can build the correct AssessmentAuth link (via Url.Action, which needs the
        /// controller's context) to pass in as <paramref name="link"/>.</param>
        /// <param name="link">The absolute AssessmentAuth URL for this invitation's token — built
        /// by the caller via Url.Action, since that requires the current controller's context.</param>
        /// <param name="assessmentDateUtc">Optional scheduled opening time, already resolved to a
        /// true UTC instant by the caller. Null means the assessment is accessible immediately
        /// (subject to eligibility/exam-window checks elsewhere).</param>
        /// <param name="durationMinutes">Override for this invitation only. 0 or less falls back
        /// to the exam's own DurationMinutes.</param>
        /// <param name="passingMarks">Override for this invitation only. 0 or less falls back to
        /// the exam's own PassingMarks.</param>
        /// <param name="expiryHours">How long the link stays valid. Clamped to 1 hour–14 days.</param>
        public AssessmentInvitation Issue(
            User candidate,
            Exam exam,
            string secureToken,
            string link,
            string[] statusesToRevoke,
            DateTime? assessmentDateUtc = null,
            int durationMinutes = 0,
            int passingMarks = 0,
            int expiryHours = DefaultExpiryHours,
            List<AssessmentInvitation>? previousInvitations = null)
        {
            // Callers issuing to a single candidate (AdminController) leave this null and we
            // query here as before. Bulk callers (RecruiterController.AssignAssessment) fetch
            // every candidate's previous invitations in one query up front and pass the
            // relevant slice in, avoiding one extra SELECT per candidate in the loop.
            var previous = previousInvitations ?? _db.AssessmentInvitations
                .Where(i => i.UserId == candidate.Id && i.ExamId == exam.Id && statusesToRevoke.Contains(i.Status))
                .ToList();
            // A replacement invitation invalidates the old link AND its one-time code: the status
            // flip blocks the link (ResolveAssessmentInvitation), and blanking the stored hash
            // means the old code can never match again even if a status check were ever relaxed.
            previous.ForEach(i =>
            {
                i.Status = "Revoked";
                i.OneTimeLoginToken = "";
            });

            // Single-candidate callers (AdminController.SendInvitation revokes only "Pending") can
            // leave an older live invitation, e.g. "Accepted", in place. Its link behaviour is
            // deliberately unchanged, but its one-time code must not survive a replacement.
            // Bulk callers pass previousInvitations and already revoke every live status.
            if (previousInvitations == null)
            {
                foreach (var live in _db.AssessmentInvitations.Where(i =>
                             i.UserId == candidate.Id && i.ExamId == exam.Id &&
                             (i.Status == "Pending" || i.Status == "Accepted")))
                {
                    live.OneTimeLoginToken = "";
                }
            }

            expiryHours = Math.Clamp(expiryHours, 1, 24 * 14);
            var resolvedDuration = Math.Clamp(durationMinutes <= 0 ? exam.DurationMinutes : durationMinutes, 5, 300);
            var resolvedPassingMarks = Math.Clamp(passingMarks <= 0 ? exam.PassingMarks : passingMarks, 1, Math.Max(1, exam.TotalMarks));

            // The raw code exists only in this method's local variable: it goes into the email
            // body below and nowhere else. The database keeps only its SHA-256 hash.
            var oneTimeCode = SecureCodeGenerator.GenerateNumericCode();

            var invitation = new AssessmentInvitation
            {
                UserId = candidate.Id,
                ExamId = exam.Id,
                Token = secureToken,
                OneTimeLoginToken = SecureCodeGenerator.HashToken(oneTimeCode),
                Status = "Pending",
                AssessmentDate = assessmentDateUtc,
                DurationMinutes = resolvedDuration,
                PassingMarks = resolvedPassingMarks,
                ExpiresAt = DateTime.UtcNow.AddHours(expiryHours),
                SentAt = DateTime.UtcNow
            };
            _db.AssessmentInvitations.Add(invitation);
            candidate.RecruitmentStage = RecruitmentStages.InvitationSent;

            _notifications.Queue(candidate, exam, "Assessment Invitation",
                $"Assessment Invitation – {ResolveRole(exam)} | {_emailOptions.SenderName}",
                BuildInvitationEmailHtml(candidate, exam, invitation, link, oneTimeCode),
                BuildInvitationInAppSummary(exam, invitation));

            return invitation;
        }

        /// <summary>True only when <paramref name="submittedCode"/> matches this invitation's
        /// stored one-time code hash and the code hasn't been used yet. The caller must already
        /// have resolved the invitation from its link token and confirmed the invitation belongs
        /// to the signing-in candidate and is still Pending/Accepted and unexpired (see
        /// AccountController.AssessmentAuth). Legacy values that aren't a SHA-256 hash (older
        /// invitations stored the code in plaintext, and it was never emailed) never match.</summary>
        public static bool IsOneTimeCodeValid(AssessmentInvitation invitation, string? submittedCode)
        {
            var code = (submittedCode ?? "").Trim();
            if (code.Length == 0 || invitation.TokenUsedAt != null) return false;

            var stored = invitation.OneTimeLoginToken ?? "";
            if (stored.Length != HashedCodeLength) return false;

            var submittedHash = SecureCodeGenerator.HashToken(code);
            return System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(
                System.Text.Encoding.ASCII.GetBytes(submittedHash),
                System.Text.Encoding.ASCII.GetBytes(stored.ToUpperInvariant()));
        }

        /// <summary>SHA-256 hex length — what HashToken returns.</summary>
        private const int HashedCodeLength = 64;

        private const string CodeStartMarker = "<!--otp-->";
        private const string CodeEndMarker = "<!--/otp-->";

        /// <summary>Removes the raw one-time code from a stored invitation email body. Called by
        /// NotificationService once the email has been handed to the mail server, so the code
        /// doesn't stay readable in dbo.Notifications after delivery.</summary>
        public static string ScrubOneTimeCode(string body)
        {
            if (string.IsNullOrEmpty(body)) return body;
            return System.Text.RegularExpressions.Regex.Replace(
                body,
                System.Text.RegularExpressions.Regex.Escape(CodeStartMarker) + ".*?" +
                System.Text.RegularExpressions.Regex.Escape(CodeEndMarker),
                "(hidden after delivery)",
                System.Text.RegularExpressions.RegexOptions.Singleline);
        }

        /// <summary>Generates a cryptographically random link token. Call this first, build the
        /// AssessmentAuth link from it, then pass both into <see cref="Issue"/>.</summary>
        public static string GenerateSecureToken() => Guid.NewGuid().ToString("N") + Guid.NewGuid().ToString("N");

        /// <summary>"Role" shown to the candidate — this schema has no standalone Job/Role
        /// entity, so, matching the existing convention in HomeController.Jobs()
        /// (OpenRoleViewModel.Role = Exam.Subject), Subject is treated as the role/job title.
        /// Falls back to the assessment Title when Subject hasn't been set.</summary>
        private static string ResolveRole(Exam exam) =>
            string.IsNullOrWhiteSpace(exam.Subject) ? exam.Title : exam.Subject;

        private static string Enc(string? s) => System.Net.WebUtility.HtmlEncode(s ?? "");

        /// <summary>HTML-encode, then turn newlines into &lt;br/&gt; — for free-text fields
        /// (Description, Instructions) that may contain line breaks worth preserving.</summary>
        private static string EncMultiline(string? s) =>
            Enc(s).Replace("\r\n", "\n").Replace("\n", "<br/>");

        /// <summary>
        /// Builds the candidate-facing assessment invitation email as a complete, corporate,
        /// responsive HTML document. Sent as-is (see NotificationService.SendGmail's
        /// rawHtmlBody path) rather than through the generic plain-text notification chrome.
        ///
        /// Deliberately excludes all internal evaluation/scoring information — Total Marks,
        /// Passing Marks, Passing Percentage, Negative Marking, cutoff, or any other
        /// evaluation criteria. It does include the one-time login code, because the sign-in
        /// page tells candidates it is sent by email (AccountController.AssessmentAuth accepts
        /// it in place of the password). The code appears only in this Email-channel body —
        /// never in the InApp summary below — and is stripped from the stored body after
        /// delivery (see <see cref="ScrubOneTimeCode"/>).
        /// </summary>
        private string BuildInvitationEmailHtml(User user, Exam exam, AssessmentInvitation invitation, string link, string oneTimeCode)
        {
            var companyName = string.IsNullOrWhiteSpace(_emailOptions.SenderName) ? "VISTAWAYS TECH" : _emailOptions.SenderName;
            var contactEmail = string.IsNullOrWhiteSpace(_emailOptions.ContactInboxEmail) ? _emailOptions.SenderEmail : _emailOptions.ContactInboxEmail;
            var role = ResolveRole(exam);

            var scheduleRow = invitation.AssessmentDate.HasValue
                ? DetailRow("Available From", $"{invitation.AssessmentDate.Value:dd MMM yyyy, HH:mm} UTC")
                : "";

            // Operational instructions only — proctoring rules describe how the candidate
            // must behave (full-screen, no copy/paste, webcam, monitoring), not how they're
            // scored, so they don't fall under the "no evaluation info" restriction.
            var proctorItems =
                (exam.RequireFullScreen       ? "<li>Keep your browser in <strong>full-screen mode</strong> throughout the assessment.</li>" : "") +
                (exam.RestrictCopyPaste       ? "<li>Copy and paste will be <strong>disabled</strong> inside the assessment window.</li>" : "") +
                (exam.RequireWebcam           ? "<li>Keep your <strong>webcam on</strong> with good lighting for the duration of the assessment.</li>" : "") +
                (exam.RequireScreenMonitoring ? "<li>Your screen activity will be <strong>monitored</strong> during the assessment.</li>" : "");

            var examInstructionsItem = !string.IsNullOrWhiteSpace(exam.Instructions)
                ? $"<li>{EncMultiline(exam.Instructions)}</li>"
                : "";

            return $@"<!DOCTYPE html>
<html lang=""en"">
<head>
  <meta charset=""UTF-8"" />
  <meta name=""viewport"" content=""width=device-width, initial-scale=1.0"" />
  <title>{Enc($"Assessment Invitation – {role}")}</title>
</head>
<body style=""margin:0;padding:0;background:#f4f4f4;font-family:Arial,Helvetica,sans-serif;"">
  <div style=""max-width:600px;margin:0 auto;padding:24px 16px;"">
    <div style=""background:#ffffff;border:1px solid #e0e0e0;border-radius:8px;overflow:hidden;"">

      <!-- Header -->
      <div style=""background:#1a1a2e;padding:24px 32px;"">
        <h1 style=""margin:0;color:#ffffff;font-size:20px;letter-spacing:0.5px;"">{Enc(companyName)}</h1>
        <p style=""margin:4px 0 0;color:#b8b8c8;font-size:12px;"">Recruitment Team</p>
      </div>

      <!-- Body -->
      <div style=""padding:32px;color:#2a2a2a;font-size:14px;line-height:1.5;"">
        <p style=""margin:0 0 16px;"">Dear {Enc(user.FullName)},</p>
        <p style=""margin:0 0 16px;"">Thank you for your interest in the <strong>{Enc(role)}</strong> position at {Enc(companyName)}.</p>
        <p style=""margin:0 0 24px;"">As part of our recruitment process, you are invited to complete the following assessment.</p>

        <!-- Assessment Details -->
        <table role=""presentation"" width=""100%"" cellpadding=""0"" cellspacing=""0"" style=""border:1px solid #e5e5e5;border-radius:6px;margin-bottom:24px;"">
          <tr><td style=""background:#f7f7fb;padding:10px 20px;border-bottom:1px solid #e5e5e5;"">
            <strong style=""font-size:12px;letter-spacing:0.5px;color:#1a1a2e;"">ASSESSMENT DETAILS</strong>
          </td></tr>
          <tr><td style=""padding:16px 20px 20px;"">
            <table role=""presentation"" width=""100%"" cellpadding=""0"" cellspacing=""0"" style=""font-size:14px;"">
              {DetailRow("Assessment", Enc(exam.Title))}
              {DetailRow("Role", Enc(role))}
              {(string.IsNullOrWhiteSpace(exam.Description) ? "" : DetailRow("Description", EncMultiline(exam.Description)))}
              {DetailRow("Duration", $"{invitation.DurationMinutes} minutes")}
              {DetailRow("Number of Questions", exam.TotalQuestions.ToString())}
              {scheduleRow}
              {DetailRow("Link Expires", $"{invitation.ExpiresAt:dd MMM yyyy, HH:mm} UTC")}
            </table>
          </td></tr>
        </table>

        <!-- Important Information -->
        <p style=""margin:0 0 8px;font-weight:bold;color:#1a1a2e;"">Important Information</p>
        <ul style=""margin:0 0 24px;padding-left:20px;"">
          <li>Please complete the assessment within the specified time.</li>
          <li>Make sure you have a stable internet connection before starting.</li>
          <li>Choose a quiet environment where you can complete the assessment without interruptions.</li>
          <li>Once you begin, the assessment timer starts immediately and cannot be paused.</li>
          <li>Please carefully read the on-screen instructions before starting.</li>
          <li>Do not refresh or close the assessment window while taking the assessment.</li>
          {examInstructionsItem}
          {proctorItems}
        </ul>

        <!-- CTA -->
        <table role=""presentation"" width=""100%"" cellpadding=""0"" cellspacing=""0"" style=""margin:0 0 24px;"">
          <tr><td align=""center"">
            <a href=""{Enc(link)}"" style=""display:inline-block;background:#1a1a2e;color:#ffffff;text-decoration:none;font-weight:bold;font-size:14px;padding:14px 36px;border-radius:6px;"">Start Assessment</a>
          </td></tr>
        </table>
        <p style=""margin:0 0 24px;font-size:12px;color:#888;text-align:center;word-break:break-all;"">
          Or copy and paste this link into your browser:<br/>
          <a href=""{Enc(link)}"" style=""color:#4a4ad0;"">{Enc(link)}</a>
        </p>

        <!-- One-time login code -->
        <table role=""presentation"" width=""100%"" cellpadding=""0"" cellspacing=""0"" style=""border:1px dashed #1a1a2e;border-radius:6px;margin:0 0 24px;"">
          <tr><td align=""center"" style=""padding:16px 20px;"">
            <p style=""margin:0 0 6px;font-size:12px;letter-spacing:0.5px;font-weight:bold;color:#1a1a2e;"">ONE-TIME LOGIN CODE</p>
            <p style=""margin:0 0 10px;font-size:28px;letter-spacing:6px;font-weight:bold;color:#1a1a2e;"">{CodeStartMarker}{Enc(oneTimeCode)}{CodeEndMarker}</p>
            <p style=""margin:0;font-size:12px;color:#666;"">On the assessment sign-in page, enter your Candidate ID or registered email and this code in the <strong>One-Time Login Token</strong> field instead of your password. The code works once, only with this invitation, and stops working when the link expires or a newer invitation is sent. Do not share it with anyone.</p>
          </td></tr>
        </table>

        <p style=""margin:0 0 12px;"">You will log in using your Candidate ID (<strong>{Enc(user.CandidateId)}</strong>) or registered email, together with your account password, or with the one-time code above.</p>
        <p style=""margin:0;"">If you have any questions regarding the assessment or the recruitment process, please contact our recruitment team at <a href=""mailto:{Enc(contactEmail)}"" style=""color:#4a4ad0;"">{Enc(contactEmail)}</a>.</p>

        <!-- Company footer (shared with the generic email layout) -->
        <div style=""margin-top:28px;"">{EmailFooter.BuildHtml()}</div>
      </div>

      <!-- Footer -->
      <div style=""background:#f7f7f7;border-top:1px solid #e5e5e5;padding:20px 32px;font-size:11px;color:#999;"">
        <p style=""margin:0 0 4px;""><strong>{Enc(companyName)}</strong> &middot; Recruitment Team</p>
        <p style=""margin:0 0 4px;"">{Enc(contactEmail)}</p>
        <p style=""margin:0;"">&copy; {DateTime.UtcNow.Year} {Enc(companyName)}. All rights reserved.</p>
      </div>

    </div>
  </div>
</body>
</html>";
        }

        private static string DetailRow(string label, string value) =>
            $@"<tr>
                <td style=""padding:4px 0;color:#777;width:170px;vertical-align:top;"">{Enc(label)}</td>
                <td style=""padding:4px 0;color:#2a2a2a;font-weight:bold;"">{value}</td>
              </tr>";

        /// <summary>Short plain-text summary for the InApp channel / dashboard notification
        /// preview (Views/Home/Index.cshtml truncates Body to ~140 chars) — the rich HTML
        /// body above is Email-only. Same no-evaluation-info rule applies.</summary>
        private static string BuildInvitationInAppSummary(Exam exam, AssessmentInvitation invitation)
        {
            var role = ResolveRole(exam);
            return $"You've been invited to complete the \"{exam.Title}\" assessment for the {role} role. " +
                   $"Duration: {invitation.DurationMinutes} minutes, {exam.TotalQuestions} question(s). " +
                   $"Check your email for the secure link, or open this assessment from your dashboard. " +
                   $"Link expires {invitation.ExpiresAt:dd MMM yyyy, HH:mm} UTC.";
        }
    }
}
