name: ExamPortal CI

on:
  push:
    branches:
      - DEV
      - master

  pull_request:
    branches:
      - DEV
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ExamPortal.sln

      - name: Build solution
        run: dotnet build ExamPortal.sln --configuration Release --no-restore
